---

# CKKS Study
### Revision 23.02.20

---

## 1. Environment

In [1]:
from ckks import CKKS
import numpy as np

## 2. Initialize 

In [2]:
M = 8
scale = 64

ckks2 = CKKS(M, scale)

## 3. Encode

$$
z_1 = (3+4i,\ 2-i)
$$

In [3]:
z1 = np.array([3 +4j, 2 - 1j])
p1 = ckks2.encode(z1)
p1

Polynomial([160.,  90., 160.,  45.], domain=[-1,  1], window=[-1,  1])

$$
z_2 = (2-3i,\ 1+i)
$$

In [4]:
z2 = np.array([2-3j, 1 +1j])
p2 = ckks2.encode(z2)
p2

Polynomial([  96.,  -23., -128.,  -68.], domain=[-1,  1], window=[-1,  1])

## 4. Encrypt

$$
c_1 = Encrypt(Encode(3+4i,\ 2-i))
$$

In [5]:
c1 = ckks2.encrypt(p1)

In [6]:
c1['b']

Polynomial([  974.,  -222.,  -882., -1641.], domain=[-1.,  1.], window=[-1.,  1.])

In [7]:
c1['a']

Polynomial([45., 66., 42., 80.], domain=[-1.,  1.], window=[-1.,  1.])

$$
c_2 = Encrypt(Encode(2-3i,1+i))
$$

In [8]:
c2 = ckks2.encrypt(p2)

In [9]:
c2['b']

Polynomial([  237.,  -737., -1910., -1616.], domain=[-1.,  1.], window=[-1.,  1.])

In [10]:
c2['a']

Polynomial([90., 35., 99., 16.], domain=[-1.,  1.], window=[-1.,  1.])

## 5. Evaluation & Decrypt

### 5.1 Addition

In [11]:
# Evaluation (add)
c_add = ckks2.HE_add(c1, c2)
c_add

{'b': Polynomial([ 1211.,  -959., -2792., -3257.], domain=[-1.,  1.], window=[-1.,  1.]),
 'a': Polynomial([135., 101., 141.,  96.], domain=[-1.,  1.], window=[-1.,  1.])}

### 5.2 Multiplication

In [12]:
# Evaluation (mult)
c_mult = ckks2.HE_mult(p2, c1)
c_mult

(Polynomial([ -72231., -313738., -315826., -175066.], domain=[-1.,  1.], window=[-1.,  1.]),
 Polynomial([16024., 18397.,  2194., -4794.], domain=[-1.,  1.], window=[-1.,  1.]))

## 6. Decrypt

In [13]:
# Decrypt c_add
add_decrypt = ckks2.add_decrypt(c_add)
add_decrypt

Polynomial([272.,  70.,  43., -12.], domain=[-1.,  1.], window=[-1.,  1.])

In [14]:
# Decrypt c_mult
mult_decrypt = ckks2.mult_decrept(c_mult)
mult_decrypt

Polynomial([ 696.59375 ,  359.796875,  -61.828125, -337.734375], domain=[-1.,  1.], window=[-1.,  1.])

## 7. Decode

In [15]:
add_decode = ckks2.decode(add_decrypt)
add_decode

array([5.15598056+1.31269052j, 3.34401944-0.03105948j])

In [16]:
mult_decode = ckks2.decode(mult_decrypt)
mult_decode

array([18.59098167-0.72230596j,  3.17757302+1.20982294j])

## 8. Comparison

### 8.1 Addition

In [17]:
# Actual addition
z1 + z2

array([5.+1.j, 3.+0.j])

In [18]:
# Homomorphic addition
add_decode

array([5.15598056+1.31269052j, 3.34401944-0.03105948j])

### 8.2 Multiplication

In [19]:
# Actual multiplication
z1 * z2

array([18.-1.j,  3.+1.j])

In [20]:
# Homomorphic multiplication
mult_decode

array([18.59098167-0.72230596j,  3.17757302+1.20982294j])

---